parameters:
    arko.serializer_extensions.array_serialization_visitor.class: Arko\SerializerExtensions\ArraySerializationVisitor
    arko.serializer.extensions.array_deserialization_visitor.class: Arko\SerializerExtensions\ArrayDeserializationVisitor
services:
    arko.serializer_extensions.array_serialization_visitor:
        class: %arko.serializer_extensions.array_serialization_visitor.class%
        tags:
            - { name: jms_serializer.serialization_visitor, format: array }
    arko.serializer_extensions.array_deserialization_visitor:
        class: %arko.serializer_extensions.array_deserialization_visitor.class%
        tags:
            - { name: jms_serializer.deserialization_visitor, format: array }